# ----- tests for fastapi endpoints @ tests/test_api/test_routes.py -----

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

try:
    from api.main import app

    client = TestClient(app)
except ImportError:
    client = None


def test_health_endpoint():
    """Test the basic health check endpoint."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_get_violations():
    """Test the violations list endpoint."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/violations")
    assert response.status_code == 200
    data = response.json()
    assert "items" in data
    assert "total" in data
    assert "page" in data


def test_get_violations_with_pagination():
    """Test the violations list endpoint with pagination params."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/violations?page=2&page_size=5")
    assert response.status_code == 200
    data = response.json()
    assert data["page"] == 2


def test_get_violation_not_found():
    """Test that a missing violation ID returns 404."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/violations/nonexistent-uuid")
    assert response.status_code == 404


def test_get_analytics_summary():
    """Test the analytics summary endpoint."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/analytics/summary")
    assert response.status_code == 200
    data = response.json()
    assert "total_violations" in data


def test_get_analytics_metrics():
    """Test that analytics metrics endpoint returns metrics or 404 when missing."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/analytics/metrics")
    # metrics.json is gitignored and only generated by `make evaluate` —
    # 404 is valid when the file doesn't exist yet
    if response.status_code == 404:
        return
    assert response.status_code == 200
    data = response.json()
    assert "detector" in data
    assert "mAP50" in data["detector"]


def test_get_evidence_image_not_found():
    """Test that a missing evidence image returns 404."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/evidence/nonexistent-uuid/image")
    assert response.status_code == 404


def test_get_evidence_metadata_not_found():
    """Test that missing evidence metadata returns 404."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/evidence/nonexistent-uuid/metadata")
    assert response.status_code == 404


def test_process_image_invalid_path():
    """Test that process endpoint returns 400 for a non-existent image path."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.post(
        "/api/violations/process",
        json={"image_path": "/nonexistent/path.jpg"},
    )
    assert response.status_code == 400


# ----- Challans API -----


def test_create_challan():
    """Test that creating a challan returns a valid challan record."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.post(
        "/api/challans",
        json={
            "violation_id": "test-vid",
            "violations": [
                {"type": "helmet", "confidence": 0.91},
                {"type": "triple_riding", "confidence": 0.85},
            ],
            "plate_number": "KA-01-AB-1234",
            "vehicle_type": "two_wheeler",
            "location": "MG Road",
            "image_hash": "abc123",
        },
    )
    assert response.status_code == 201
    data = response.json()
    assert data["challan_id"] is not None
    assert data["fine_total"] == 2000  # 1000 + 1000
    assert data["status"] == "pending"
    assert data["violation_id"] == "test-vid"


def test_get_challans():
    """Test that the challans list endpoint returns paginated data."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/challans")
    assert response.status_code == 200
    data = response.json()
    assert "items" in data
    assert "total" in data
    assert "page" in data
    assert len(data["items"]) >= 1  # from the previous create test


def test_get_challan_not_found():
    """Test that a missing challan ID returns 404."""
    if client is None:
        pytest.fail("FastAPI app not implemented yet!")

    response = client.get("/api/challans/nonexistent-uuid")
    assert response.status_code == 404
